### ISSUE TITLE
Under MSYS64 shell: Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'tmp'  Key being added: 'tmp'

### ISSUE THREAD

**Issue by Russtopia** [lachesis/scallion#109]
Runs OK for me under cmd.exe, but would like to use within MSYS2 shell for better scripting ability (I'm more of a UNIX/Linux type)
--
Windows 7 x64, binary download, latest version as of 2017-05-04
[Run from MSYS2 x64 shell]

$ ./scallion -l
Id:0 Name:GeForce GTX 750 Ti
    PreferredGroupSizeMultiple:32 ComputeUnits:5 ClockFrequency:1110
    MaxConstantBufferSize:65536 MaxConstantArgs:9 MaxMemAllocSize:536870912

$ ./scallion foo
Cooking up some delicions scallions...
Using kernel optimized from file kernel.cl (Optimized4)
Using work group size 32
Compiling kernel... done.
Testing SHA1 hash...
CPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
GPU SHA-1: d3486ae9136e7856bc42212385ea797094475802
Looks good!
LoopIteration:1  HashCount:16.78MH  Speed:798.9MH/s  Runtime:00:00:00  Predicted:00:00:00  Found new key! Found 1 unique keys.

Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'tmp'  Key being added: 'tmp'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.StringDictionary.Add(String key, String value)
   at System.CodeDom.Compiler.Executor.ExecWaitWithCaptureUnimpersonated(SafeUserTokenHandle userToken, String cmd, String currentDir, TempFileCollection tempFiles, String& outputName, String& errorName, String trueCmdLine)
   at System.CodeDom.Compiler.Executor.ExecWaitWithCapture(SafeUserTokenHandle userToken, String cmd, String currentDir, TempFileCollection tempFiles, String& outputName, String& errorName, String trueCmdLine)
   at Microsoft.CSharp.CSharpCodeGenerator.Compile(CompilerParameters options, String compilerDirectory, String compilerExe, String arguments, String& outputFile, Int32& nativeReturnValue, String trueArgs)
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource(CompilerParameters options, String[] sources)
   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type)
   at scallion.Util.ToXml[T](T obj, TextWriter writer) in C:\Users\FreeTop\projects\scallion\scallion\Util.cs:line 35
   at scallion.Util.ToXml[T](T obj) in C:\Users\FreeTop\projects\scallion\scallion\Util.cs:line 19
   at scallion.CLRuntime.Run(ProgramParameters parms) in C:\Users\FreeTop\projects\scallion\scallion\CLRuntime.cs:line 496
   at scallion.Program.Main(String[] args) in C:\Users\FreeTop\projects\scallion\scallion\Program.cs:line 433

Stopping the GPU and shutting down...

Running with -n doesn't crash, but no keys are found (at least within ~1min of running)

**Comment by JeSTeRFLA** [comment]
i got about the sameish

┌─[root@--]─[tor]
└──╼ #mono scallion/bin/Debug/scallion.exe -l
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'OpenSSL.Core.Native' threw an exception. ---> System.EntryPointNotFoundException: ERR_load_crypto_strings
  at (wrapper managed-to-native) OpenSSL.Core.Native:ERR_load_crypto_strings ()
  at OpenSSL.Core.Native..cctor () [0x00080] in <38c0e4f76c27429fb3b78d7e3d807f68>:0
   --- End of inner exception stack trace ---
  at OpenSSL.Core.ThreadInitialization.InitializeThreads () [0x00001] in <38c0e4f76c27429fb3b78d7e3d807f68>:0
  at scallion.Program.Main (System.String[] args) [0x00008] in <1229c4d7c88140dba1cf0e6bed5a8c08>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'OpenSSL.Core.Native' threw an exception. ---> System.EntryPointNotFoundException: ERR_load_crypto_strings
  at (wrapper managed-to-native) OpenSSL.Core.Native:ERR_load_crypto_strings ()
  at OpenSSL.Core.Native..cctor () [0x00080] in <38c0e4f76c27429fb3b78d7e3d807f68>:0
   --- End of inner exception stack trace ---
  at OpenSSL.Core.ThreadInitialization.InitializeThreads () [0x00001] in <38c0e4f76c27429fb3b78d7e3d807f68>:0
  at scallion.Program.Main (System.String[] args) [0x00008] in <1229c4d7c88140dba1cf0e6bed5a8c08>:0
