### ISSUE TITLE
 System.TypeInitializationException Error

### ISSUE THREAD

**Issue by ghost** [lachesis/scallion#110]
`C:\tor>scallion -o domain.txt -k 1024 -d 0 mydomain

Unhandled Exception: System.TypeInitializationException: The type initializer for 'OpenSSL.Core.Native' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libeay32': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OpenSSL.Core.Native.ERR_load_crypto_strings()
   at OpenSSL.Core.Native..cctor() in C:\Users\FreeTop\projects\scallion\openssl-net-0.5\ManagedOpenSsl\Core\Native.cs:line 172
   --- End of inner exception stack trace ---
   at OpenSSL.Core.Native.InitializeThreads()
   at OpenSSL.Core.ThreadInitialization.InitializeThreads() in C:\Users\FreeTop\projects\scallion\openssl-net-0.5\ManagedOpenSsl\Core\Native.cs:line 103
   at scallion.Program.Main(String[] args) in C:\Users\FreeTop\projects\scallion\scallion\Program.cs:line 306`

i dont know why i see error i dont have this directory C:\Users\FreeTop\projects\scallion\openssl-net-0.5\ManagedOpenSsl\Core\

**Comment by ghost** [comment]
i am using Windows Server 2016 . with Nvidia Tesla K80
i installed Mono  .NET Framework 3.5 VC++ Redistributable 2008 Java etc 
what else i need to do

**Comment by ghost** [comment]
i forget to mention i am using Google Cloud GPU server . Remote Desktop PC

**Comment by techsoulman** [comment]
I have the exact same problem on my Windows 10 PC with a NVIDIA GeForce GTX 1060 6GB.
I'm new at all this but I'm pretty sure I have completed the same steps as mrsajid808.

Does anyone have any advice for this?

**Comment by arafey** [comment]
I'm having a similar error in Arch Linux:
```
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'OpenSSL.Core.Native' threw an exception. ---> System.EntryPointNotFoundException: ERR_load_crypto_strings
  at (wrapper managed-to-native) OpenSSL.Core.Native:ERR_load_crypto_strings ()
  at OpenSSL.Core.Native..cctor () [0x0007a] in <913f4f16195c4c2fb936c8880dd033f1>:0 
   --- End of inner exception stack trace ---
  at OpenSSL.Core.ThreadInitialization.InitializeThreads () [0x00001] in <913f4f16195c4c2fb936c8880dd033f1>:0 
  at scallion.Program.Main (System.String[] args) [0x00007] in <7606088bd7384e8cb4e858b4c87a9411>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'OpenSSL.Core.Native' threw an exception. ---> System.EntryPointNotFoundException: ERR_load_crypto_strings
  at (wrapper managed-to-native) OpenSSL.Core.Native:ERR_load_crypto_strings ()
  at OpenSSL.Core.Native..cctor () [0x0007a] in <913f4f16195c4c2fb936c8880dd033f1>:0 
   --- End of inner exception stack trace ---
  at OpenSSL.Core.ThreadInitialization.InitializeThreads () [0x00001] in <913f4f16195c4c2fb936c8880dd033f1>:0 
  at scallion.Program.Main (System.String[] args) [0x00007] in <7606088bd7384e8cb4e858b4c87a9411>:0
```
Not sure if this is the Linux analog or an unrelated problem.

**Comment by Arinerron** [comment]
Yep, getting the same error. edit: on arch too.

**Comment by VanVan** [comment]
Working on Windows 10, but same problem on Windows server 2012 and 2016

**Comment by ghost** [comment]
also having this problem. im on a windows server 2016 GCP free trial and im using a nvidia tesla v100 gpu. and i tried both the original and 2.0.

**Comment by fosslinux** [comment]
can repro on debian

**Comment by mgdudas** [comment]
Same on Ubuntu 19.04

**Comment by ObscenityIB** [comment]
Same as @arafey on Kali, latest rolling release.

Only thing i see wrong is that mono no longer supports the old .NET that scallion uses
